# Jdbc Driver Settings
# パスワードを暗号化したいなどのニーズがある場合などは設定を外だしにすることも可能
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ixui-example?useSSL=false
    username: root
    password: Password_1
    driverClassName: com.mysql.cj.jdbc.Driver


# MyBatis Settings
mybatis:
  mapper-locations: classpath*:/mapper/**.xml
  configuration.map-underscore-to-camel-case: true
  type-aliases-package: jp.co.ixui.example.base.case001.domain,jp.co.ixui.example.base.case001.mapper
  configuration.call-setters-on-nulls: true
